version: "3.8"
services:
  backtester:
    build:
      context: .
      network: host
      args:
        HTTP_PROXY: http://127.0.0.1:7890
        HTTPS_PROXY: http://127.0.0.1:7890
        http_proxy: http://127.0.0.1:7890
        https_proxy: http://127.0.0.1:7890
    command: bash
    volumes:
      - ./:/app
    tty: true
    stdin_open: true
